### ISSUE TITLE
Feature Request: add a links to modules in Module Manager

### ISSUE THREAD

**Issue by geoidesic** [sdenec/tidy-ui_game-settings#39]
Currently if you're in game and want to know what a module does, you have to either go do a search for it on google or you have to quit your game and go back to Settings so that you can view the Add-on Modules tab where there are links to the developer pages. 

It would be so much better if one had access to those links from the Manage Modules pop-up in-game.

**Comment by sdenec** [comment]
I have no control over what is displayed there only how. But just toggle the full description for modules (default button since a few foundry releases) and you have the link to the author's devpage. Hope that helps?

![full-description](https://user-images.githubusercontent.com/8881200/103168787-89aa3800-4836-11eb-8f71-bef05d0496b2.jpg)
